### ISSUE TITLE
Is it possible to integrate custom golang code?

### ISSUE THREAD

**Issue by adderly** [daptin/daptin#100]
Just find out the project, and after reading the little documentation there is.

Many questions are unanswered. Is there a undocumented way to add a plugin ?

It would be nice to have some examples.

**Comment by artpar** [comment]
Hi @adderly 

What kind of plugins are you thinking ?

**Comment by adderly** [comment]
Hello @artpar,

In the first instance, i will need to add some mobile notification integration and a payment gateway.

Both of those cases would be advised to do it in the backend.

Also i would like to integrate like a html editor/ blog editor into the backend, as of now i have no idea how difficult it is to do so with daptin.

So to implement such things, will be controlled by the api. Maybe i will need to change my way of viewing this?

**Comment by artpar** [comment]
Hi @adderly 

For mobile notification and payment gateway integrations (basically server side 3rd party calls) you can construct your own action APIs. Action API allow you to do a wide variety of things including calling 3rd party APIs on server to server side and also handle custom payload for 3rd party callback/hook APIs.

Checkout here a YAML which creates 2 Actions APIs for paypal integration which the frontend can use

https://github.com/daptin/daptin-schema-samples/blob/master/pay-via-paypal/schema_pay_by_paypal_daptin.yaml

It defines 2 actions
 - buy_package -> this initiates a payment, user to be redirected to paypal site after this call
 - mark_as_complete_by_paypal -> handles s2s call from paypal, marks the order complete

For sale/transaction (inventory management) api example, refer to this: https://github.com/daptin/daptin-schema-samples/blob/master/transactions-and-payments/schema_transaction_and_payments_daptin.yaml

Once this yaml is imported, your daptin instance will have 2 extra actions which the ui can call for the payment flow.

For html editor/blog editor, this is even easier, since you only need to build a frontend. Check this example of an image gallery application:

https://github.com/daptin/image-gallery

You can upload markdown files instead of images and render to html for users on frontend.

**Comment by adderly** [comment]
Hello again,

As i stumble through daptin, not knowing where to start.

I haven't been able to run the image-gallery example, i can't seem to correctly set it up.

The main objective i have is running a site locally.

@artpar where can i join the slack channel?

**Comment by artpar** [comment]
Hi

You can join slack group with this link

https://join.slack.com/t/daptin/shared_invite/enQtMzM1NTM1NTkyMDgzLWJmZmRlN2M4YzRkOTI4MDhlNWQ1YzBiMDNhMzE0NTVmNzA3NjA5ZDdkMDExZmI0M2UyMmM2NzhlNDc3M2VhZTQ

I recommend you start using daptin with a UI first, I am building one here 

https://github.com/daptin/dadadash/

You can quickly try it out using docker:

`docker run -p 8080:8080 daptin/dadadash`

Than point your browser to `localhost:8080` where once you create account you will be presented with this

![workspace-create](https://user-images.githubusercontent.com/1142886/100535723-7e68ea00-3241-11eb-873c-76374e39aaf4.png)

Switch to the administrator view 

![change-to-admin-view](https://user-images.githubusercontent.com/1142886/100535760-ca1b9380-3241-11eb-956c-bd272bee5b03.png)
![admin-dashboard-home](https://user-images.githubusercontent.com/1142886/100535761-cc7ded80-3241-11eb-9fb2-c00fc1845f2b.png)

Now you can begin to customize your instance by adding tables and actions. Dadadash is still WIP so some things might break.
