### ISSUE TITLE
Where is the Web Dashboard?

### ISSUE THREAD

**Issue by BubbaJoe** [daptin/daptin#103]
Where is the source for this dashboard? https://github.com/daptin/daptin#web-dashboard

There are no links or any info in this is section.

I am not referring to dadadash. That dashbaord is different that the one in this section.

**Comment by artpar** [comment]
Hi @BubbaJoe 

That was the first implementation of a dashboard for daptin.

It was phased out due to being very generic and simplistic in nature (just exposes all the features as table entries). It should be possible to build yourself (npm install && npm run build should be enough)

https://github.com/daptin/daptin/tree/dashboard-old/daptinweb

Dadadash is also trying expose all the features of daptin one by one, but in a more contextual manner. You need to switch to the "Administrator" part of dadadash to see those.

**Comment by artpar** [comment]
Hi @BubbaJoe 

I have pulled out the dashboard-classic code from the branch here into its own repository. Docker image is also ready to use. Check it out here

https://github.com/daptin/dashboard-classic

```docker run -p 8080:8080 daptin/dashboard-classic```

Will add more details in the readme there.

Regards
