### ISSUE TITLE
No go due to several issues

### ISSUE THREAD

**Issue by JLKM** [daptin/daptin#104]
Having followed this awesome project for almost two years I've just had the present release up for a spin.

Still love all the features - yaml schemas, email, OAuth etc. However the short encounter turned out to be a dissapointment:

1. Saving table definitions for the first time was really responsive. But the relations never got saved.
2. Afterwards I never succeded in editing and saving changes in neither columns nor relations. Error message: `Table name already used`!
3. Furthermore I never found the `Become admin` button mentioned in the docs.

Had really looked forward to testing a just-before-version-1.0, but the issues mentioned above are real showstoppers. My deepest regrets.

Platform: Windows 10
Exe: https://github.com/daptin/daptin/releases/download/v0.9.2/daptin-windows-4.0-386.exe

**Comment by artpar** [comment]
Hi @JLKM 

Appreciate that you took time to give this another try. Sadly the issues you are facing is not due to daptin but the new dashboard which I am building for it. 

The dashboard has been moved to its own repo here: https://github.com/daptin/dadadash

1. Question here: did you add the relations when creating the table or when editing the table ?
  1.1 The relationship would be fail to add if you don't mark them as nullable and table has existing data.

2. Pushed a fix in https://github.com/daptin/dadadash/commit/a6f93d9f18ca372829b6b77efbe54d9fc379e208 
  2.1 This should fix the "Table name already used" error on editing existing table

3. "Become admin" now automatically triggers for the first user if you are using dadadash

The docs are sadly lagging behind on the UI front (hence the instructions for "Become admin" manually which was required in the dashboard classic https://github.com/daptin/dashboard-classic)

I'll go ahead and test out the points 1.1 and 2.2 once again when the build is complete, before marking this as resolved.

**Comment by JLKM** [comment]
Thank you for your quick response.

> Did you add the relations when creating the table or when editing the table?

Answer: Both. And the relations wouldn't stick either way after save. Yet, the error message `Table name already used` only showed up after editing the previously saved settings.

Possible explanation: My test included two `has one` relations (foreign keys). The two related fieldnames in the relations were set up as aliases. But I didn't mark the aliases as nullables.

I would very much like to take the project for another spin. But how do I most easily get a version with your updates - and also a working combination of the two libraries (API and dashboard). I guess there will be no executable available for this.

**Comment by artpar** [comment]
Hi

I was able to track down both the cause for both the issues and pushed a fix in dadadash.

For the other question as to the most easy way to follow update, until v1 I am not planning to add any major feature in daptin. All the minor fixes/commits which are pushed are automatically built and pushed as ```daptin/daptin:travis``` docker image, so that tag is bleeding edge. After testing I tag the stable images with the `:latest` tag. Also backward compatibility is one of the priorities.

Binaries are built for all commits and tagged releases will have the binaries for all platforms + docker image available. Plan is to embed the dashboard build in the static binary itself (which is not happening right now, only the docker image is carrying the dashboard).

I am not sure if that answers your last question. For the services I am using daptin, I pull the latest image/binary once in a while. Keeping up with the latest release is also not necessary unless there is a security issue or a patch you need.

**Comment by JLKM** [comment]
Thank you for filling me in. However, I'm not familiar with docker or running `:something`. Guess I'll just wait for a new release with exe-file included.

**Comment by artpar** [comment]
Hi

Have created a new release. Tested the two issues you faced explicitly. 

The dashboard is embedded in the binary executable so you can try it easily

https://github.com/daptin/daptin/releases/tag/v0.9.4
