### ISSUE TITLE
I am using mysql, how optimize the generated table names?

### ISSUE THREAD

**Issue by zplzpl** [daptin/daptin#109]
e.g:

```
user_otp_account_user_otp_account_id_has_usergroup_usergroup_id
```

**Comment by artpar** [comment]
Hi @zplzpl 

What do you mean by optimizing the names ?

Daptin manages the table names, column names, relationship table names (for many to many), index names, foreign key names internally so that they don't clash with each other. 

The table name you mentioned is a join table (a user otp account can belong to multiple user groups). Join table names follow this convection:

<SubjectTableName>_<SubjectColumnName>_has_<ObjectTableName>_<ObjectColumnName>

**Comment by zplzpl** [comment]
Is the name generation rule configurable?

**Comment by artpar** [comment]
The name generation rule for join tables isn't configurable as of now.

How would you have configured it. What kind of configuration are you looking for. Only join table names are generated and join tables are not usually directly accessed. If you are facing some other issue because of names, do bring it up.

**Comment by zplzpl** [comment]
It's too long for me

**Comment by artpar** [comment]
Do you have a better approach for the names ? The names the slightly long for my taste as well but this is the only way I see to avoid any conflicts.

Consider the case when there can be multiple many to many joins between two tables or even a self join.

Lets say you have table t1 and t2, each with 2 columns: col1 and col2. Now we make a many to many join table for these two tables on t1.col1 = t2.col2. What would you name the join table for this ?

**Comment by artpar** [comment]
@zplzpl The join table names are configurable. Like I mentioned the join table name structure, when defining a relation, you can set the 4 params:

```yaml
- Subject: <Table> 
  SubjectName: defaults to <Table>_id
  Object: <OtherTable>
  ObjectName: defaults to <OtherTable>_id
```
You will need to ensure there are no conflicts when defining multiple relations, as the subject_name and object_name also become part of the exposed API.
