### ISSUE TITLE
Add Social login/register - normalize email

### ISSUE THREAD

**Issue by benfavre** [daptin/daptin#17]
Any thought on adding social login/register ?
Great work so far !!

Daptin is something I think far more people will realize is the only thing you need when making an API based site.
You are ahead of the competition as far as I can tell from my various tests.

**Comment by artpar** [comment]
Yes, social login/register is already half ready. It is directly built over the Oauth connections, there is a option to enable it once you add create one. So it enables actually enables a couple of API to handle the flow and create a corresponding user for itself.

On the dashboard part you would be able to see a "Login using <Oauth connection name>" to checkout the flow. This WILL come up in current builds but the work is not complete yet. Have to connect a few pieces.

**Comment by benfavre** [comment]
I acknowledge some things are subject to change and you have stuff in progress right now even tought it's functional, but docs for the cloud hosting and various oauth stuff, migh go a long way.

**Comment by artpar** [comment]
Yes, I have started writing since a couple of weeks now, have been able to cover some surface of it. Check them here:

https://docs.dapt.in/cloudstore/cloudstore/
https://docs.dapt.in/extend/oauth_connection/
https://docs.dapt.in/extend/oauth_token/

But a lot more to cover. For now I am trying to figure out the traffic from ga which documentations should I write up first. For ex https://docs.dapt.in/setting-up/settingup/ is a little more details then the rest of the pages.

Maintaining a copy of the documentations site on github as well: https://daptin.github.io/docs/

**Comment by artpar** [comment]
Have completed the ground work for the end to end flow. We have a couple of new features in the by-product as well

- Default data on system bootstrap: this will allow to get ready to work deployments easily (compared to deploy + configure)
- A set of groups to which all newly created objects of a type will be added
  - a "users" usergroup is present by default
  - new users from oauth login flow will be added to "users" usergroup
  - "users" group has sane defaults access-rules for couple of parts of the system (actions and dashboard)

Have pushed the related work in the branch `social-login-oauth-connections`. Will try it out with a couple of more providers before merging in master (currently only tested with google login)

**Comment by artpar** [comment]
Tested with the following providers

- Google 
- Dropbox
- Github
- LinkedIn
