### ISSUE TITLE
Best way to decode JWT in NodeJS or PHP

### ISSUE THREAD

**Issue by benfavre** [daptin/daptin#18]
Looking to share the auth JWT token to authenticate the user for another service I have.
Are you doing anything special or can I just decode the token by fetching the key you generate on init ?
Thanks.

**Comment by artpar** [comment]
There are three relevant actions:

## Oauth flow start
https://github.com/daptin/daptin/blob/master/server/resource/action_oauth_login_begin.go

This is an action which you can invoke using action API 
```
{
		Name:     "oauth.login.begin",
		Label:    "Authenticate via OAuth",
		OnType:   "oauth_connect",
		InFields: []api2go.ColumnInfo{},
		OutFields: []Outcome{
			{
				Type:   "oauth.client.redirect",
				Method: "EXECUTE",
				Attributes: map[string]interface{}{
					"authenticator": "$.name",
					"scope":         "$.scope",
				},
			},
		},
},
```
## Oauth response

This generates a oauth token. Could be a JWT token or otherwise. It will be returned to the client.

The response is handled by the [oauth login response action](https://github.com/daptin/daptin/blob/master/server/resource/columns.go#L587) which invokes these two:

https://github.com/daptin/daptin/blob/master/server/resource/action_oauth_login_response.go

## Profile exchange 

This is a separate action to get user profile using the token (since the implementation differs across providers). You probably don't need this for JWT token.

https://github.com/daptin/daptin/blob/master/server/resource/action_oauth_profile_exchange.go

The ```DoAction``` method will contain the most interesting parts.

So if you invoke this flow, you will get a copy of the token in response (to your client). Depending on you want to store the token or not, you can create a new action (editing the above).

> can I just decode the token by fetching the key you generate on init ?

Yes. The keys in ```_config``` table are to be used to decrypt "encrypted" fields.

**Comment by benfavre** [comment]
Thanks for the detailed answer
