### ISSUE TITLE
Unable to login after logout

### ISSUE THREAD

**Issue by JLKM** [daptin/daptin#42]
Get more and more impressed by this tool. But I still haven't been able to login twice (login after first logout). Just get:

> Unauthorized
> Request failed with status code 403

> I failed to Signin

Have both tried to clean browser cache and restart Daptin-server. Still no access.

Some log for possible clarification:

```
[36mINFO[0m[4106] Find all row by params: [smd]: map[world_id:[d4f04a34-dcb3-4125-9167-2003c93e387e] worldName:[smd_id]]
[GIN] 2018/10/26 - 22:12:32 |[97;42m 200 [0m|      2.9997ms |             ::1 |[97;44m GET     [0m /static/fonts/WOFF2/TTF/SourceSansPro-Regular.ttf.woff2
[36mINFO[0m[4106] Query: SELECT smd.created_at, smd.updated_at, smd.name, smd.label, smd.initial_state, smd.events, smd.user_account_id, smd.permission, smd.reference_id FROM smd JOIN  world_world_id_has_smd_smd_id j1 on j1.smd_id = smd.id join world on j1.world_id = world.id  WHERE world.reference_id IN (?) LIMIT 10 OFFSET 0 == [d4f04a34-dcb3-4125-9167-2003c93e387e]
[36mINFO[0m[4106] Relation [oauth_connect][[TableRelation] [oauth_connect_id][belongs_to][user_account_id]]
[36mINFO[0m[4106] Relation [oauth_connect][[TableRelation] [oauth_connect_id][has_many][usergroup_id]]
[36mINFO[0m[4106] Relation [oauth_connect][[TableRelation] [oauth_token_id][has_one][oauth_connect_id]]
[GIN] 2018/10/26 - 22:12:32 |[97;42m 200 [0m|      1.9986ms |             ::1 |[97;44m GET     [0m /static/fonts/WOFF2/TTF/SourceSansPro-Bold.ttf.woff2
[GIN] 2018/10/26 - 22:12:32 |[97;42m 200 [0m|     15.9916ms |             ::1 |[97;44m GET     [0m /jsmodel/oauth_connect.js
[GIN] 2018/10/26 - 22:12:32 |[97;42m 200 [0m|      1.0062ms |             ::1 |[97;44m GET     [0m /static/fonts/WOFF2/TTF/SourceSansPro-Light.ttf.woff2
[36mINFO[0m[4106] Find all row by params: [oauth_connect]: map[page[number]:[1] page[size]:[500] query:[W3siY29sdW1uIjoiYWxsb3dfbG9naW4iLCJvcGVyYXRvciI6ImlzIiwidmFsdWUiOiIxIn1d]]
[36mINFO[0m[4106] Found query in request: W3siY29sdW1uIjoiYWxsb3dfbG9naW4iLCJvcGVyYXRvciI6ImlzIiwidmFsdWUiOiIxIn1d
[31mERRO[0m[4106] Failed to unmarshal query as json, using as a filter instead: invalid character 'W' looking for beginning of value
[36mINFO[0m[4106] Query: []
[36mINFO[0m[4106] Query: SELECT oauth_connect.created_at, oauth_connect.updated_at, oauth_connect.name, oauth_connect.client_id, oauth_connect.client_secret, oauth_connect.scope, oauth_connect.response_type, oauth_connect.redirect_uri, oauth_connect.auth_url, oauth_connect.token_url, oauth_connect.profile_url, oauth_connect.profile_email_path, oauth_connect.allow_login, oauth_connect.user_account_id, oauth_connect.permission, oauth_connect.reference_id FROM oauth_connect WHERE ( oauth_connect.name like ? or oauth_connect.client_id like ? or oauth_connect.response_type like ? or oauth_connect.profile_email_path like ?) LIMIT 500 OFFSET 0 == [%W3siY29sdW1uIjoiYWxsb3dfbG9naW4iLCJvcGVyYXRvciI6ImlzIiwidmFsdWUiOiIxIn1d% %W3siY29sdW1uIjoiYWxsb3dfbG9naW4iLCJvcGVyYXRvciI6ImlzIiwidmFsdWUiOiIxIn1d% %W3siY29sdW1uIjoiYWxsb3dfbG9naW4iLCJvcGVyYXRvciI6ImlzIiwidmFsdWUiOiIxIn1d% %W3siY29sdW1uIjoiYWxsb3dfbG9naW4iLCJvcGVyYXRvciI6ImlzIiwidmFsdWUiOiIxIn1d%]
[GIN] 2018/10/26 - 22:12:32 |[97;42m 200 [0m|      9.9875ms |             ::1 |[97;44m GET     [0m /api/oauth_connect?page[number]=1&page[size]=500&query=W3siY29sdW1uIjoiYWxsb3dfbG9naW4iLCJvcGVyYXRvciI6ImlzIiwidmFsdWUiOiIxIn1d
[GIN] 2018/10/26 - 22:12:57 |[97;43m 403 [0m|      6.9944ms |             ::1 |[97;46m POST    [0m /action/user_account/signin
[GIN] 2018/10/26 - 22:13:09 |[97;43m 403 [0m|      8.9892ms |             ::1 |[97;46m POST    [0m /action/user_account/signin
```

**Comment by artpar** [comment]
Hi @JLKM,

One question: Did you "Become admin" after the first sign in ?

**If no**, is it possible for you to give me a dump of your daptin setup, the download JSON Schema and JSON Dump (backup section on dashboard)  will contain the entirety of the setup, which I can try out on my local.

**If yes**, that is the reason you are unable to sign in again. I will try to explain why and whats the way to enable it.

On a fresh installation of daptin, it is "open for all" system, meaning anyone can call any API/Action and that's why the first user can "sign up". When you "Become admin", Daptin reset the permission for all APIs and Actions to be allowed only for "authorized people" (logged in people). This effectively disables sign-ups/sign-in (because signup/signin can only be done by guests).

To enable sign-in/sign-up, you will need to change the permission for the "user_account" entity and allow "actions" to be performed by guests. To do this:

- Go do dashboard
- Left side bar -> Administration -> "All tables"
- Filter the "user_account" table
- Click the expand icon for it so we can proceed to edit it

<img width="1431" alt="screen shot 2018-10-29 at 12 32 19 pm" src="https://user-images.githubusercontent.com/1142886/47634220-c0ad3200-db76-11e8-9f2b-81cd5471d23a.png">

Notice the screen shot I have attached is before I clicked "Become admin", the permissions is set to "127127127", which means allow everything for everyone  ( checkout this page for a detailed explaination https://daptin.github.io/docs/auth/authorization/ which should make some sense if you have worked with linux file system permissions)

Once I become admin, the permission for all tables will be changed to 127127067 (so owners and group are allowed everything but guests can only Read and Refer). I have written about what these permissions do here https://daptin.github.io/docs/auth/permissions/


<img width="1416" alt="screen shot 2018-10-29 at 12 35 44 pm" src="https://user-images.githubusercontent.com/1142886/47634357-48933c00-db77-11e8-9dc5-d25894709363.png">

Click the pencil icon on the top right to edit the entity, come down to "Permission" (do note there is a  "Default permission" field also which is meant for something else).

Under Permission, click the "Guest" table and Check "Execute" and save it.

<img width="1080" alt="screen shot 2018-10-29 at 12 37 40 pm" src="https://user-images.githubusercontent.com/1142886/47634467-a3c52e80-db77-11e8-8ce7-283d4d1df75f.png">

One more step is required to bring this into effect, go to "Dashboard" and click "Restart". Daptin will restart itself and new permission will be in effect. You should be able to login now.

Do note that "become admin" can be triggered only once. You can add more administrators by adding users to the "administrators" user group.

**Comment by artpar** [comment]
Also, my bad that I missed this part in the documentation/walk-thrus, I will update them so it will be more helpful :) And thanks for the kind words. Its a huge encouragement.

**Comment by artpar** [comment]
One more point:

If you logout after "becoming admin" without enabling sign-in, the system is effectively locked (unless you have SQL access to the database where you can set the permissions and restart daptin). You will need to do a clean setup if you don't have access to the database directly.

**Comment by phanikumar252** [comment]
hi, i have been tryng to creat a new account from my website using backend as daptin but everytime i am getting 403 forbidden error .Please help to resolve this issue thank you.
![screenshot at 2019-02-15 12 27 21](https://user-images.githubusercontent.com/47655676/52839725-1523ef80-311d-11e9-800b-7dd67478b975.png)
