### ISSUE TITLE
Unable to install packages

### ISSUE THREAD

**Issue by phanikumar252** [daptin/daptin#51]
hi @artpar ,

i am trying to download a package from market place as you said in how to install column by going through this link https://github.com/daptin/market.  
i didn't find any list in market place so please help me on this thank you.
![screenshot at 2019-02-16 11 54 03](https://user-images.githubusercontent.com/47655676/52895514-a65c9a00-31e1-11e9-9aff-229a2b29d0b3.png)

**Comment by artpar** [comment]
Hi @phanikumar252,

The marketplace API allowes you to manage your schemas in a git repository smoothly. So for example this market (https://github.com/daptin/market) has couple of sample schemas I have created for testing. You can install any schema from this repo. 

Here are the steps:

https://docs.dapt.in/extend/marketplace/

You can skip the "Create a repo" step and instead use this repo: https://github.com/daptin/market

**Comment by phanikumar252** [comment]
hi @artpar ,

I have tried what you said but i am getting internal server error.  Can i please have any more suggestions on this issue. Thank you
![screenshot at 2019-02-18 19 09 51](https://user-images.githubusercontent.com/47655676/52954835-2d13a180-33b1-11e9-9e01-cc2c7ab03310.png)

**Comment by artpar** [comment]
Hey @phanikumar252 

I am sorry I missed adding a step there. You need to click the "Refresh marketplace" once after adding so that daptin will pull the packages from there.

Checkout the following screenshots:

<img width="1428" alt="screen shot 2019-02-19 at 9 51 27 am" src="https://user-images.githubusercontent.com/1142886/52990050-4e65a380-342c-11e9-8f19-c479e2533107.png">

<img width="1451" alt="screen shot 2019-02-19 at 9 51 46 am" src="https://user-images.githubusercontent.com/1142886/52990049-4e65a380-342c-11e9-8ddf-eba49b9f8d4a.png">

<img width="1447" alt="screen shot 2019-02-19 at 9 52 02 am" src="https://user-images.githubusercontent.com/1142886/52990048-4e65a380-342c-11e9-9e39-b1871324518b.png">

When you install a package, use the exact name as the folder name, for example "blog" (without quotes)

After installation I can see the 3 new entities ready to use:

<img width="1436" alt="screen shot 2019-02-19 at 9 55 43 am" src="https://user-images.githubusercontent.com/1142886/52990103-8ff64e80-342c-11e9-9eda-547f75cfd3a3.png">

**Comment by phanikumar252** [comment]
hi @artpar ,

I refresh the marketplace after adding eventhough when i am trying to install package i am getting same error please check the corresponding screenshot. Thank you.
![screenshot at 2019-02-18 19 09 51](https://user-images.githubusercontent.com/47655676/52991320-3c86ff00-3432-11e9-9ad3-5b3f6cce46f2.png)

**Comment by phanikumar252** [comment]
hi @artpar ,

I am sorry i have added wrong endpoint now i modified it. So i am able to install packages now. Thank yiu for your support.
