### ISSUE TITLE
Docs image not display

### ISSUE THREAD

**Issue by Chris533** [daptin/daptin#70]
Hi Parth

1.Pictures are normal  a few days ago.

2.Dashboard has not "Execute strict"
> Dashboard -> All tables -> Search "User" and locate the "User account" entity -> Edit -> Permissions -> Guests -> Check "Execute strict"

Is the documents correct or need to be updated?

https://daptin.github.io/daptin/setting-up/settingup/#enable-sign-up

**Comment by Chris533** [comment]
![image](https://user-images.githubusercontent.com/17868145/73609340-85b26d80-4607-11ea-8127-1049bed7380e.png)

Thansk.

**Comment by artpar** [comment]
1. Docs issue

So its not a bug actually

I plan to host docs permanent at https://docs.dapt.in/ and since its the same source of both these (https://daptin.github.io/docs/) one of them has broken images.

Do note that I am yet to add documentation for a variety of features. Writing docs is hard.

The current docs should mostly be up to date but missing stuff

2. Permissions

Yes so this is something old in docs, There was a major rework in permissions part once after writing the docs, for now you can skip the references to the "strict" parts in permission docs.

I will try to update the docs.

**Comment by artpar** [comment]
Feel free to hit up on slack

https://join.slack.com/t/daptin/shared_invite/enQtMzM1NTM1NTkyMDgzLTVlYzBlMmM4YjMyOTk0MDc5MWJmMzFlMTliNzQwYjcxMzc5Mjk0YzEyZDIwYTljZmE5NDU3Yjk3YzQ3MzhkMzI

I guess the slack invite link on read me isn't very noticeable.

**Comment by Chris533** [comment]
Sorry Parth, link is no longer active, check please, I will try later.

**Comment by artpar** [comment]
The slack link ?

**Comment by Chris533** [comment]
Yes

**Comment by artpar** [comment]
Try this

https://join.slack.com/t/daptin/shared_invite/enQtMzM1NTM1NTkyMDgzLWJmZmRlN2M4YzRkOTI4MDhlNWQ1YzBiMDNhMzE0NTVmNzA3NjA5ZDdkMDExZmI0M2UyMmM2NzhlNDc3M2VhZTQ

Another bug caught :-/

**Comment by Chris533** [comment]
I'm in, thanks : )
