### ISSUE TITLE
Why I did not choose daptin

### ISSUE THREAD

**Issue by guettli** [daptin/daptin#99]
I am looking for a headless CMS.

I did not choose daption.

Do you know why?

It is a one-man-show: https://github.com/daptin/daptin/graphs/contributors

Almost all commits where done by one person. What will happen if this person gets hit by bus?

Yes, daptin looks good and it is amazing what one person was able to create.

**Comment by artpar** [comment]
Hi @guettli 

I understand when you mention bus factor of a project as a reason for depending on it. So I would like to bring out couple of points to give you a complete picture

## Dependencies
- While most of the code committed in daptin is by a single contributor, you can also consider that daptin is mostly glue code connecting several different libraries together, some of the major ones pulling the gears:
  - github.com/rclone/rclone
  - github.com/emersion/go-imap
  - github.com/buraksezer/olric
  - github.com/go-acme/lego/v3
  - github.com/gohugoio/hugo
  - github.com/manyminds/api2go
  - github.com/Masterminds/squirrel


## Feature planning
- The plan for daptin is not to continuously add features forever. 
- There is nothing in daptin in one of our own file formats. 
- The jsonapi.org interface exposes tables which are all in third normal form or on disk transparently (asset columns/sites)
- The standards exposed are stable and not going anywhere soon
  - HTTP/HTTPS
  - GraphQL
  - SMTP
  - IMAP/IMAPS
  - FTP
  - Acme/LetsEncrypt
  - OpenAPI


So overall you can see the goal is to get it stable and stop there. As you would have also noticed from the commit chart that the activity in daptin has been much less recently. The code base is not huge and relevantly straightforward so that any professional golang developer will be able to pick it up easily.

## Open source 
Is naturally a protection against bus factors.

Love to hear more from you

Regards

**Comment by guettli** [comment]
Thank you for your answer. I think you have clear road-map. That's cool. And think you know much more than I do. I wish you all the best!

**Comment by artpar** [comment]
Anyone reading this, daptin would love contributors.
